### ISSUE TITLE
Unable to use UUID's as permanent ids

### ISSUE THREAD

**Issue by almilli** [nilbus/Backbone.dualStorage#117]
DualStorage uses UUIDs as the temporary id generator.  And detects the id being a temporary id as one that looks like a UUID.  This means that it's impossible to use DualStorage out of the box if the server also uses UUIDs as the permanent id.  I can see this being a very common use case.  What ends up happening is that DualStorage never issues "remote" server commands when inserting/updating/deleting items.   You should change it to use temporary ids that are something more unique instead of using a standard for real ids.

In order to get this to work, I had to override the temporary id generation and check.  I just prepended a "t" to a UUID so it was a different length than a normal UUID.

```
    Backbone.Model.prototype.hasTempId = function() {
         return _.isString(this.id) && this.id.length === 37;
    };
    window.Store.prototype.generateId = function() {
         return "t" + uuid.v4();
    }
```

**Comment by nilbus** [comment]
Released in v1.4.0.
