### ISSUE TITLE
No way to replace onlineSync behaviour after loading

### ISSUE THREAD

**Issue by rtibbles** [nilbus/Backbone.dualStorage#123]
This is more about convenience - but as the backboneSync method that onlineSync uses doesn't appear to be available anywhere it means I can't modify it conveniently from within my app.

If there is a way to do it, do let me know - otherwise, I have made a small change on my fork to namespace backboneSync under Backbone.DualStorage so that it can be patched by my app. Happy to submit a PR if wanted - all tests pass apart from the two that seemed to be failing before I modified anything.

**Comment by nilbus** [comment]
Released in v1.4.0.
