### ISSUE TITLE
syncDirtyAndDestroyed() doesn't remove/clear ###_dirty in localStorage

### ISSUE THREAD

**Issue by Cinezaster** [nilbus/Backbone.dualStorage#129]
Hi,
After a syncDirtyAndDestroyed() on a collection the "###_dirty" still contains an id of a model. I get a status-code 200 from the server. Since dualStorage is not fetching models that are in the dirty list our app get stuck on models that are marked dirty.

I cannot find in the code where the ###_dirty is cleared

**Comment by nilbus** [comment]
Check out `Store.clean` and the places where `clean` is called, in `localsync` update and delete. Once you figure out the scenario that creates this error condition, we can create a failing spec that reproduces it and fix the issue.

**Comment by Cinezaster** [comment]
If I run `syncDirtyAndDestroyed();` should I pass through `localsync` function? Because it doesn't.

**Comment by nilbus** [comment]
```coffeescript
Backbone.Collection.prototype.syncDirty = (options) ->
  store = localStorage.getItem("#{getStoreName(@)}_dirty")
  ids = (store and store.split(',')) or []

  for id in ids
    @get(id)?.save(null, options)
```

For each id marked dirty, it tries to get the model from the collection by that id. If a model with that id exists, it will try to save it. Save should call sync, which is overridden to be [dualsync](https://github.com/nilbus/Backbone.dualStorage/blob/master/backbone.dualstorage.coffee#L244).

```coffeescript
dualsync = (method, model, options) ->
  # ...

  # execute only online sync
  return onlineSync(method, model, options) if _.result(model, 'remote') or _.result(model.collection, 'remote')

  # execute dual sync
  # ...
```

If neither the model nor collection have a truthy `remote` property, then it will continue to try to dualsync. Double-check this.

As dualsync executes, `localsync` generally always gets called below [backbone.dualstorage.coffee:283](https://github.com/nilbus/Backbone.dualStorage/blob/master/backbone.dualstorage.coffee#L283). Trace the execution to see what's actually happening.

**Comment by Cinezaster** [comment]
Got it. The response on the PUT call is empty, but status is 200. Backbone handles this as an error but since the error is never logged I didn't know the call was not successful. I fixed this by adding
```
  Backbone.ajax = function() {
    var args = Array.prototype.slice.call(arguments, 0);
    if (args[0].type === 'PUT') {
        args[0].dataType = "text";
    }
    return Backbone.$.ajax.apply(Backbone.$, args);
};```


This is not a bug in this library. A bit of error feedback would be nice.
