### ISSUE TITLE
using .toJSON(options) instead of JSON.stringify in create()/update() store methods

### ISSUE THREAD

**Issue by hippich** [nilbus/Backbone.dualStorage#131]
Some third-party backbone plugins rely on options value passed when updating/creating model at backend (that's how stock Backbone.sync works.) Because dualStorage do not pass options nor call .toJSON() - other code breaks.

Would it be reasonable to change dualStorage to pass `options` all the way down to create/update methods of Store and call .toJSON(options) on model instead of JSON.stringify()? Should be trivial change, but I want to hear if JSON.stringify() was used for a reason.

**Comment by nilbus** [comment]
No, I don't think there was any reason. I would be happy to accept a pull request with that change, as long as the test suite stays green.
