### ISSUE TITLE
xhr 200 result of an error

### ISSUE THREAD

**Issue by CharlesNo** [nilbus/Backbone.dualStorage#137]
Hi all,

Well, I don't know why, but on my case I need to add this code in each options.error before the return:

```javascript
if (xhr.status == 200) {
    return options.success();
}
```

Even if the request return 200 "OK", it goes on the error callback.

I'm testing this under a Phonegap serve, contacting a localhost webservice (Express with Node.js, REST routes respecting RESTful *rules*).

Maybe it trigger an error because I'm under "phonegap serve" and I know it proxy all requests.
If you want more information don't hesitate to ask me.
Know it works really great.

Kind regards,
Charles

**Comment by nilbus** [comment]
Thanks Charles. What operations do you need this for? Both save and fetch? Is this a good example of what you're talking about?

```javascript
someModel.save({}, error: function(xhr) {
  if (xhr.status == 200) {
    return options.success();
  }
});

**Comment by nilbus** [comment]
Thanks Charles. What operations do you need this for? Both save and fetch? Is this a good example of what you're talking about?

```javascript
var options = {
  success: function() {…},
  error: function(xhr) {
    if (xhr.status == 200) {
      return options.success();
    }
  }
};
someModel.save({}, options);

**Comment by CharlesNo** [comment]
Hi nilbus,

I just found the root of this problem. My server (nodejs/express) was sending a res.sendStatus(200).
But res.json({}) is working well.
So why ?
For a put, if the Content-type is not application/json, it is considered as an error.
res.sendStatus respond with a Content-type: text/...

My bad.

(thanks to this thread: http://stackoverflow.com/questions/21181133/backbone-model-save-returning-error-while-server-sending-200ok )

Regards

**Comment by nilbus** [comment]
Glad you got it sorted out
