### ISSUE TITLE
Model.parse should not be called in dualsync

### ISSUE THREAD

**Issue by raffomania** [nilbus/Backbone.dualStorage#142]
`dualsync` calls `modelUpdatedWithResponse` for every model when reading a collection. This causes every model to be parsed twice: once via `modelUpdatedWithResponse` and once when being added to its collection. 
I believe the original backbone implementation only calls `Model.parse` in methods like `fetch`, `reset` etcetera. Shouldn't dualStorage handle it the same way?

**Comment by nilbus** [comment]
I think this is the same issue as #111, right? Beyond the description, you may want to read the last comment. I don't have a fix yet; no one has been working on it. Are you comfortable with trying to come up with a solution that keeps everything working that we talk about in #111?

**Comment by raffomania** [comment]
Oh, you're right, I found that ticket but didn't read the comments closely enough. I'm going to have a look at that ticket!

**Comment by nilbus** [comment]
Cool. Let me know if you want to take a stab at it.
