### ISSUE TITLE
QuotaExceededError

### ISSUE THREAD

**Issue by wojciecheu** [nilbus/Backbone.dualStorage#150]
I am developing mobile app based on Phonegap / Cordova. Sometimes there is lack of internet connection. This plugin works fine on that situation, but sometimes there is problem with localStorage (throws QuotaExceededError if length exceeds about 5 MB - it is browser specific thing). Probably that storage in Webwiev is not efficent as expected. Maybe it would be better using WebSQL with Persistence.js - we can set its capacity up to  50MB.

**Comment by nilbus** [comment]
Yes, you are correct that localstorage is full. You can either work on efficiency or use an IndexedDB (or deprecated WebSQL) backend instead. See https://github.com/nilbus/Backbone.dualStorage/issues/149#issuecomment-136005569 and #73 on how to use other backends with this library.
